"""Assemble a standalone Aseprite build.lua for one sprite sheet."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from mason.core.assets import (
    PIXEL_TRANSPARENT,
    RasterLayer,
    SpriteSheetSpec,
)
from mason.core.styles import StyleProfile, hex_rgba
from mason.errors import MasonError


def sheet_layout(spec: SpriteSheetSpec) -> dict[str, Any]:
    """Compute the packed grid and per-frame rects for frames.json.

    One animation per row, columns = longest animation. Unused cells
    stay empty/transparent. Returns the Mason frames contract plus
    sheet dimensions the Lua exporter uses.
    """
    fw, fh = spec.canvas.width, spec.canvas.height
    cols = max(len(anim.frames) for anim in spec.animations)
    rows = len(spec.animations)
    animations = []
    for row, anim in enumerate(spec.animations):
        frames = []
        for col, frame in enumerate(anim.frames):
            frames.append({
                "index": col,
                "x": col * fw,
                "y": row * fh,
                "w": fw,
                "h": fh,
                "duration_ms": frame.duration_ms,
            })
        animations.append({
            "name": anim.name,
            "loop": anim.loop,
            "frames": frames,
        })
    return {
        "frame_size": {"width": fw, "height": fh},
        "sheet": {"width": cols * fw, "height": rows * fh},
        "columns": cols,
        "rows": rows,
        "animations": animations,
    }


def resolve_layer(layer: RasterLayer, style: StyleProfile) -> dict[str, Any]:
    """Resolve palette keys on one layer into RGBA for the Lua script."""
    if layer.text or layer.image:
        raise MasonError(
            f"Layer '{layer.name}' uses text/image; sprite_sheet "
            "frames are fill+rect or pixels.",
            code="sprite_layer_unsupported",
            hint="Draw glyphs as pixels, or import via a later pipeline.",
            context={"layer": layer.name},
        )
    entry: dict[str, Any] = {"name": layer.name}
    if layer.fill:
        entry["fill"] = hex_rgba(style.color(layer.fill))
    if layer.rect:
        entry["rect"] = layer.rect.model_dump()
    if layer.pixels:
        keys: dict[str, list[int]] = {}
        for row in layer.pixels:
            for ch in row:
                if ch in PIXEL_TRANSPARENT:
                    continue
                keys[ch] = hex_rgba(style.color(layer.keys[ch]))
        entry["pixels"] = layer.pixels
        entry["keys"] = keys
    return entry


def build_aseprite_script(
    spec: SpriteSheetSpec,
    style: StyleProfile,
    job_dir: Path,
) -> str:
    """Return a self-contained Aseprite Lua script."""
    layout = sheet_layout(spec)
    animations = []
    for anim in spec.animations:
        frames = []
        for frame in anim.frames:
            frames.append({
                "duration_ms": frame.duration_ms,
                "layers": [resolve_layer(ly, style) for ly in frame.layers],
            })
        animations.append({
            "name": anim.name,
            "loop": anim.loop,
            "frames": frames,
        })
    root = job_dir.resolve()
    payload = {
        "job_dir": root.as_posix(),
        "name": spec.name,
        "canvas": {
            "width": spec.canvas.width,
            "height": spec.canvas.height,
        },
        "columns": layout["columns"],
        "rows": layout["rows"],
        "save_aseprite": spec.export.aseprite,
        "save_png": spec.export.png,
        "aseprite_path": (root / "output" / "asset.aseprite").as_posix(),
        "png_path": (root / "output" / "asset.png").as_posix(),
        "animations": animations,
    }
    return (
        "-- Generated by Mason. Standalone Aseprite script.\n"
        f"local CONFIG = {_lua_value(payload)}\n"
        + _BODY
    )


def _lua_value(value: Any) -> str:
    """Encode a Python value as a Lua literal."""
    if value is None:
        return "nil"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, list):
        inner = ", ".join(_lua_value(v) for v in value)
        return "{" + inner + "}"
    if isinstance(value, dict):
        parts = []
        for key, item in value.items():
            if isinstance(key, str) and key.isidentifier():
                lhs = key
            else:
                lhs = f"[{_lua_value(key)}]"
            parts.append(f"{lhs}={_lua_value(item)}")
        return "{" + ", ".join(parts) + "}"
    raise TypeError(f"cannot encode {type(value)} as Lua")


_BODY = r'''

local function color_of(rgba)
  return Color{
    r=rgba[1], g=rgba[2], b=rgba[3], a=rgba[4] or 255,
  }
end

local function draw_rect(img, rect, rgba)
  local col = color_of(rgba)
  local x1 = rect.x
  local y1 = rect.y
  local x2 = rect.x + rect.width - 1
  local y2 = rect.y + rect.height - 1
  for y = y1, y2 do
    for x = x1, x2 do
      img:putPixel(x, y, col)
    end
  end
end

local function draw_pixels(img, rows, keys)
  for y, row in ipairs(rows) do
    local x = 0
    for ch in string.gmatch(row, ".") do
      local rgba = keys[ch]
      if rgba then
        img:putPixel(x, y - 1, color_of(rgba))
      end
      x = x + 1
    end
  end
end

local function draw_layers(img, layers)
  for _, layer in ipairs(layers) do
    if layer.fill then
      if layer.rect then
        draw_rect(img, layer.rect, layer.fill)
      else
        img:clear(color_of(layer.fill))
      end
    end
    if layer.pixels then
      draw_pixels(img, layer.pixels, layer.keys)
    end
  end
end

local function set_cel_image(spr, layer, frame_i, img)
  local cel = layer:cel(frame_i)
  if cel then
    cel.image = img
    cel.position = Point(0, 0)
  else
    spr:newCel(layer, frame_i, img, Point(0, 0))
  end
end

local function write_error(err)
  local path = CONFIG.job_dir .. "/lua_error.txt"
  local f = io.open(path, "w")
  if f then
    f:write(tostring(err))
    f:close()
  end
end

local function build()
  local w = CONFIG.canvas.width
  local h = CONFIG.canvas.height
  local spr = Sprite(w, h)
  app.activeSprite = spr
  local layer = spr.layers[1]
  layer.name = "sprite"

  local frame_i = 1
  for _, anim in ipairs(CONFIG.animations) do
    local from = frame_i
    for _, frame in ipairs(anim.frames) do
      if frame_i > 1 then
        spr:newFrame()
      end
      local img = Image(ImageSpec{
        width=w, height=h, colorMode=ColorMode.RGB, transparentColor=0,
      })
      img:clear()
      draw_layers(img, frame.layers)
      set_cel_image(spr, layer, frame_i, img)
      spr.frames[frame_i].duration = frame.duration_ms / 1000
      frame_i = frame_i + 1
    end
    local tag = spr:newTag(from, frame_i - 1)
    tag.name = anim.name
  end

  if CONFIG.save_aseprite then
    spr:saveAs(CONFIG.aseprite_path)
  end

  if CONFIG.save_png then
    local cols = CONFIG.columns
    local rows = CONFIG.rows
    local sheet = Image(ImageSpec{
      width=cols * w,
      height=rows * h,
      colorMode=ColorMode.RGB,
      transparentColor=0,
    })
    sheet:clear()
    local fi = 1
    for row, anim in ipairs(CONFIG.animations) do
      for col, _ in ipairs(anim.frames) do
        local cel = layer:cel(fi)
        if cel then
          sheet:drawImage(cel.image, Point((col - 1) * w, (row - 1) * h))
        end
        fi = fi + 1
      end
    end
    sheet:saveAs(CONFIG.png_path)
  end
end

local ok, err = pcall(build)
if not ok then
  write_error(err)
  error(err)
end
'''
