"""Assemble a standalone Krita build.py for one job."""

from __future__ import annotations

import json
from pathlib import Path

from mason.core.assets import LayeredRasterSpec
from mason.core.styles import StyleProfile


def build_krita_script(
    spec: LayeredRasterSpec,
    style: StyleProfile,
    job_dir: Path,
    width: int,
    height: int,
) -> str:
    """Return a self-contained Krita Python script."""
    layers = []
    for layer in spec.layers:
        entry = {
            "name": layer.name,
            "fill": style.color(layer.fill),
        }
        if layer.rect:
            entry["rect"] = layer.rect.model_dump()
        layers.append(entry)
    payload = {
        "job_dir": str(job_dir.resolve()),
        "name": spec.name,
        "width": width,
        "height": height,
        "save_kra": spec.export.kra,
        "save_png": spec.export.png,
        "layers": layers,
    }
    return (
        _HEADER
        + json.dumps(payload, indent=2)
        + "\n''')\n"
        + _BODY
    )


_HEADER = """# Generated by Mason. Standalone Krita script.
import json
import os

from krita import InfoObject, Krita

CONFIG = json.loads(r'''
"""

_BODY = r'''
def hex_to_bgra(value):
    """Convert #RRGGBB to BGRA bytes."""
    text = value.strip().lstrip("#")
    r = int(text[0:2], 16)
    g = int(text[2:4], 16)
    b = int(text[4:6], 16)
    return bytes((b, g, r, 255))


def fill_layer(layer, color, x, y, w, h):
    """Write a solid BGRA rectangle into a paint layer."""
    pixel = hex_to_bgra(color)
    layer.setPixelData(pixel * (w * h), x, y, w, h)


def write_metadata(path, layer_names):
    payload = {
        "width": CONFIG["width"],
        "height": CONFIG["height"],
        "layer_count": len(layer_names),
        "layers": layer_names,
    }
    with open(path, "w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2)


def main():
    job_dir = CONFIG["job_dir"]
    output = os.path.join(job_dir, "output")
    previews = os.path.join(job_dir, "previews")
    os.makedirs(output, exist_ok=True)
    os.makedirs(previews, exist_ok=True)
    app = Krita.instance()
    w = int(CONFIG["width"])
    h = int(CONFIG["height"])
    doc = app.createDocument(w, h, CONFIG["name"], "RGBA", "U8", "", 72.0)
    root = doc.rootNode()
    for child in list(root.childNodes()):
        root.removeChildNode(child)
    names = []
    for layer in CONFIG["layers"]:
        node = doc.createNode(layer["name"], "paintlayer")
        root.addChildNode(node, None)
        rect = layer.get("rect")
        if rect:
            fill_layer(
                node,
                layer["fill"],
                int(rect["x"]),
                int(rect["y"]),
                int(rect["width"]),
                int(rect["height"]),
            )
        else:
            fill_layer(node, layer["fill"], 0, 0, w, h)
        names.append(layer["name"])
    doc.refreshProjection()
    kra = os.path.join(output, "asset.kra")
    png = os.path.join(output, "asset.png")
    preview = os.path.join(previews, "full.png")
    if CONFIG["save_kra"]:
        doc.saveAs(kra)
    info = InfoObject()
    if CONFIG["save_png"]:
        doc.exportImage(png, info)
    doc.exportImage(preview, info)
    write_metadata(os.path.join(output, "metadata.json"), names)
    doc.close()


main()
'''
