"""Assemble a standalone Blender build.py for one job."""

from __future__ import annotations

import json
from pathlib import Path

from mason.core.assets import PropPart, StaticPropSpec
from mason.core.styles import StyleProfile
from mason.generators.blender.export import EXPORT_SRC
from mason.generators.blender.materials import CREATE_MATERIAL_SRC
from mason.generators.blender.preview_scene import PREVIEW_SCENE_SRC
from mason.generators.blender.primitives import CREATE_BOX_SRC


def build_blender_script(
    spec: StaticPropSpec,
    style: StyleProfile,
    parts: list[PropPart],
    job_dir: Path,
    *,
    bevel_width: float,
    bevel_segments: int,
    roughness: float,
    metallic: float,
    part_textures: dict[str, str] | None = None,
) -> str:
    """Return a self-contained Blender Python script.

    part_textures: maps a part's `name` to a resolved PNG path (see
    `resolve_part_textures`), for parts to use as an Image Texture
    base color instead of a flat palette color.
    """
    palette = {part.material: style.color(part.material) for part in parts}
    # always include primary
    try:
        palette.setdefault("primary", style.color(spec.materials.primary))
    except Exception:
        pass
    payload = {
        "job_dir": str(job_dir.resolve()),
        "save_blend": spec.export.save_blend,
        "bevel": spec.geometry.bevel,
        "bevel_width": bevel_width,
        "bevel_segments": bevel_segments,
        "roughness": roughness,
        "metallic": metallic,
        "resolution": [
            style.render.resolution.width,
            style.render.resolution.height,
        ],
        "samples": style.render.samples,
        "engine": style.render.engine,
        "lighting_preset": style.lighting.preset,
        "families": {
            key: fam.model_dump(mode="json")
            for key, fam in style.materials.families.items()
        },
        "palette": palette,
        "part_textures": part_textures or {},
        "tile_size": style.textures.tile_size,
        "wrap": style.textures.wrap,
        "parts": [p.model_dump(mode="json") for p in parts],
    }
    return (
        _HEADER
        + json.dumps(payload, indent=2)
        + "\n''')\n"
        + _BODY
    )


_HEADER = '''# Generated by Mason. Standalone Blender 4.x script.
import json
import os
import sys

import bpy
from mathutils import Vector

CONFIG = json.loads(r\'\'\'
'''

_BODY = (
    CREATE_BOX_SRC
    + CREATE_MATERIAL_SRC
    + EXPORT_SRC
    + PREVIEW_SCENE_SRC
    + r'''
def reset_scene():
    """Delete all objects so the build is deterministic."""
    for obj in list(bpy.data.objects):
        bpy.data.objects.remove(obj, do_unlink=True)
    for mesh in list(bpy.data.meshes):
        bpy.data.meshes.remove(mesh)
    for mat in list(bpy.data.materials):
        bpy.data.materials.remove(mat)
    for cam in list(bpy.data.cameras):
        bpy.data.cameras.remove(cam)
    for light in list(bpy.data.lights):
        bpy.data.lights.remove(light)


def family_settings(part):
    """Resolve roughness/metallic/variation for one part."""
    families = CONFIG.get("families") or {}
    name = part.get("family")
    if name and name in families:
        return families[name]
    return {
        "roughness": CONFIG["roughness"],
        "metallic": CONFIG["metallic"],
        "variation": 0.0,
    }


def build_geometry():
    """Create parts, materials, bevels, and UVs."""
    mats = {}

    def solid_material(part, key):
        settings = family_settings(part)
        wear = float(part.get("wear") or 0.0)
        cache = (key, part.get("family"), wear)
        if cache not in mats:
            hex_color = CONFIG["palette"].get(key) or CONFIG["palette"].get(
                "primary",
            )
            mats[cache] = create_material(
                f"{key}_{len(mats)}",
                hex_color,
                settings["roughness"],
                settings["metallic"],
                settings.get("variation") or 0.0,
                wear,
            )
        return mats[cache]

    tex_mats = {}

    def texture_material(image_path, part):
        """Cache one material per distinct texture path."""
        settings = family_settings(part)
        if image_path not in tex_mats:
            tex_mats[image_path] = create_textured_material(
                f"tex_{len(tex_mats)}",
                image_path,
                settings["roughness"],
                settings["metallic"],
                CONFIG["wrap"],
            )
        return tex_mats[image_path]

    created = {}
    for part in CONFIG["parts"]:
        obj = create_primitive(part)
        created[obj.name] = obj
        is_plane = (part.get("shape") or "box") == "plane"
        tex_path = CONFIG["part_textures"].get(part["name"])
        if tex_path:
            assign_material(obj, texture_material(tex_path, part))
        else:
            key = part.get("material") or "primary"
            if key in CONFIG["palette"] or "primary" in CONFIG["palette"]:
                assign_material(obj, solid_material(part, key))
        use_bevel = part.get("bevel")
        if use_bevel is None:
            use_bevel = CONFIG["bevel"]
        if use_bevel and not is_plane:
            apply_bevel(obj, CONFIG["bevel_width"], CONFIG["bevel_segments"])
        if tex_path and is_plane:
            # A textured plane is a decal (label/sign face): fit the
            # whole image to the one face instead of tiling it.
            unwrap_stretch(obj)
        else:
            unwrap_cube(obj, CONFIG["tile_size"])
    for part in CONFIG["parts"]:
        parent_name = part.get("parent")
        child = created.get(part["name"])
        parent = created.get(parent_name) if parent_name else None
        if child is not None and parent is not None:
            world = child.matrix_world.copy()
            child.parent = parent
            child.matrix_parent_inverse = parent.matrix_world.inverted()
            child.matrix_world = world


def parse_mode():
    argv = sys.argv
    if "--" in argv:
        extra = argv[argv.index("--") + 1:]
    else:
        extra = []
    if "--mode" in extra:
        return extra[extra.index("--mode") + 1]
    return "all"


def main():
    mode = parse_mode()
    job_dir = CONFIG["job_dir"]
    output = os.path.join(job_dir, "output")
    previews = os.path.join(job_dir, "previews")
    os.makedirs(output, exist_ok=True)
    os.makedirs(previews, exist_ok=True)
    blend = os.path.join(output, "asset.blend")
    if mode in ("all", "build"):
        reset_scene()
        build_geometry()
        if CONFIG["save_blend"]:
            save_blend(blend)
        export_glb(os.path.join(output, "asset.glb"))
    if mode in ("all", "preview"):
        if mode == "preview" and os.path.isfile(blend):
            bpy.ops.wm.open_mainfile(filepath=blend)
        render_previews(
            previews,
            CONFIG["resolution"],
            CONFIG["samples"],
            CONFIG.get("engine") or "eevee",
        )
    if mode in ("all", "build"):
        write_metadata(os.path.join(output, "metadata.json"))


if __name__ == "__main__":
    main()
'''
)
