"""Assemble a standalone Blender build.py for one job."""

from __future__ import annotations

import json
from pathlib import Path

from mason.core.assets import PropPart, StaticPropSpec
from mason.core.styles import StyleProfile
from mason.generators.blender.export import EXPORT_SRC
from mason.generators.blender.materials import CREATE_MATERIAL_SRC
from mason.generators.blender.preview_scene import PREVIEW_SCENE_SRC
from mason.generators.blender.primitives import CREATE_BOX_SRC


def build_blender_script(
    spec: StaticPropSpec,
    style: StyleProfile,
    parts: list[PropPart],
    job_dir: Path,
    *,
    bevel_width: float,
    bevel_segments: int,
    roughness: float,
    metallic: float,
) -> str:
    """Return a self-contained Blender Python script."""
    palette = {part.material: style.color(part.material) for part in parts}
    # always include primary
    try:
        palette.setdefault("primary", style.color(spec.materials.primary))
    except Exception:
        pass
    payload = {
        "job_dir": str(job_dir.resolve()),
        "save_blend": spec.export.save_blend,
        "bevel": spec.geometry.bevel,
        "bevel_width": bevel_width,
        "bevel_segments": bevel_segments,
        "roughness": roughness,
        "metallic": metallic,
        "resolution": [
            style.render.resolution.width,
            style.render.resolution.height,
        ],
        "samples": style.render.samples,
        "engine": style.render.engine,
        "palette": palette,
        "parts": [p.model_dump(mode="json") for p in parts],
    }
    return (
        _HEADER
        + json.dumps(payload, indent=2)
        + "\n''')\n"
        + _BODY
    )


_HEADER = '''# Generated by Mason. Standalone Blender 4.x script.
import json
import os
import sys

import bpy
from mathutils import Vector

CONFIG = json.loads(r\'\'\'
'''

_BODY = (
    CREATE_BOX_SRC
    + CREATE_MATERIAL_SRC
    + EXPORT_SRC
    + PREVIEW_SCENE_SRC
    + r'''
def reset_scene():
    """Delete all objects so the build is deterministic."""
    for obj in list(bpy.data.objects):
        bpy.data.objects.remove(obj, do_unlink=True)
    for mesh in list(bpy.data.meshes):
        bpy.data.meshes.remove(mesh)
    for mat in list(bpy.data.materials):
        bpy.data.materials.remove(mat)
    for cam in list(bpy.data.cameras):
        bpy.data.cameras.remove(cam)
    for light in list(bpy.data.lights):
        bpy.data.lights.remove(light)


def build_geometry():
    """Create parts, materials, and bevels."""
    mats = {}
    for key, hex_color in CONFIG["palette"].items():
        mats[key] = create_material(
            key,
            hex_color,
            CONFIG["roughness"],
            CONFIG["metallic"],
        )
    created = {}
    for part in CONFIG["parts"]:
        obj = create_primitive(part)
        created[obj.name] = obj
        key = part.get("material") or "primary"
        if key in mats:
            assign_material(obj, mats[key])
        use_bevel = part.get("bevel")
        if use_bevel is None:
            use_bevel = CONFIG["bevel"]
        if use_bevel and (part.get("shape") or "box") != "plane":
            apply_bevel(obj, CONFIG["bevel_width"], CONFIG["bevel_segments"])
    for part in CONFIG["parts"]:
        parent_name = part.get("parent")
        child = created.get(part["name"])
        parent = created.get(parent_name) if parent_name else None
        if child is not None and parent is not None:
            world = child.matrix_world.copy()
            child.parent = parent
            child.matrix_parent_inverse = parent.matrix_world.inverted()
            child.matrix_world = world


def parse_mode():
    argv = sys.argv
    if "--" in argv:
        extra = argv[argv.index("--") + 1:]
    else:
        extra = []
    if "--mode" in extra:
        return extra[extra.index("--mode") + 1]
    return "all"


def main():
    mode = parse_mode()
    job_dir = CONFIG["job_dir"]
    output = os.path.join(job_dir, "output")
    previews = os.path.join(job_dir, "previews")
    os.makedirs(output, exist_ok=True)
    os.makedirs(previews, exist_ok=True)
    blend = os.path.join(output, "asset.blend")
    if mode in ("all", "build"):
        reset_scene()
        build_geometry()
        if CONFIG["save_blend"]:
            save_blend(blend)
        export_glb(os.path.join(output, "asset.glb"))
    if mode in ("all", "preview"):
        if mode == "preview" and os.path.isfile(blend):
            bpy.ops.wm.open_mainfile(filepath=blend)
        render_previews(
            previews,
            CONFIG["resolution"],
            CONFIG["samples"],
            CONFIG.get("engine") or "eevee",
        )
    if mode in ("all", "build"):
        write_metadata(os.path.join(output, "metadata.json"))


if __name__ == "__main__":
    main()
'''
)
