"""ImageMagick image_process pipeline."""

from __future__ import annotations

import json
import shutil
from pathlib import Path

from PIL import Image

from mason.core.assets import HeightToNormalOp, ImageProcessSpec
from mason.core.jobs import AssetJob
from mason.core.results import BuildResult, ValidationCheck, ValidationReport
from mason.core.styles import StyleProfile
from mason.errors import MasonError
from mason.generators.imagemagick.commands import (
    build_magick_args,
    expected_size,
    last_format,
    resolve_source,
)
from mason.pipelines.common import finish_result, tool_failed
from mason.tools.imagemagick.adapter import ImageMagickAdapter
from mason.tools.registry import require_tool


def build_image_process(
    spec: ImageProcessSpec,
    style: StyleProfile,
    job: AssetJob,
    source_spec: str | None,
    *,
    mode: str = "all",
) -> BuildResult:
    """Run magick ops, write preview, validate."""
    info = require_tool("imagemagick")
    job.prepare()
    job.write_spec(spec)
    job.write_style(style)
    job.write_meta(source_spec)
    source = resolve_source(spec, job)
    if not source.is_file():
        raise MasonError(
            f"Source image not found: {source}",
            code="source_missing",
            hint="Build the source asset first, or fix the path.",
            context={"source": str(source)},
        )
    fmt = last_format(spec)
    dest = job.output / f"asset.{fmt}"
    preview = job.previews / "full.png"

    adapter = ImageMagickAdapter()
    exe = Path(info.path) if info.path else None
    normal_op = next(
        (
            op for op in spec.operations
            if isinstance(op, HeightToNormalOp)
        ),
        None,
    )
    magick_ops = [
        op for op in spec.operations
        if not isinstance(op, HeightToNormalOp)
    ]
    if mode != "preview":
        if magick_ops:
            args = build_magick_args(spec, style, job, source, dest)
            job.build_py.write_text(
                "# ImageMagick argv (generated by Mason)\n"
                + json.dumps([info.path, *args], indent=2)
                + "\n",
                encoding="utf-8",
            )
            result = adapter.execute(
                args,
                cwd=job.dir,
                executable=exe,
                stdout_path=job.stdout_log,
                stderr_path=job.stderr_log,
            )
            if not result.success:
                raise tool_failed(
                    job, result.command, result.exit_code, "imagemagick",
                )
            exit_code = result.exit_code
        else:
            shutil.copy2(source, dest)
            exit_code = 0
        if normal_op:
            from mason.generators.raster.normal import height_to_normal
            height_to_normal(dest, dest, normal_op.strength)
    else:
        if not dest.is_file():
            raise MasonError("No processed image to preview.", code="missing_output")
        exit_code = 0

    _write_preview(dest, preview, adapter, exe, job)
    _write_metadata(job, spec, dest)
    report = validate_image_process(job, spec, dest, preview, exit_code)
    outputs = {"image": job.rel(dest)}
    previews = {"full": job.rel(preview)} if preview.is_file() else {}
    return finish_result(
        job,
        spec,
        tool="imagemagick",
        version=info.version,
        outputs=outputs,
        previews=previews,
        report=report,
        source_spec=source_spec,
    )


def _write_preview(
    dest: Path,
    preview: Path,
    adapter: ImageMagickAdapter,
    exe: Path | None,
    job: AssetJob,
) -> None:
    if dest.suffix.lower() == ".png":
        shutil.copy2(dest, preview)
        return
    adapter.execute(
        [dest.as_posix(), preview.as_posix()],
        cwd=job.dir,
        executable=exe,
        stdout_path=job.dir / "preview_stdout.log",
        stderr_path=job.dir / "preview_stderr.log",
    )


def _write_metadata(
    job: AssetJob,
    spec: ImageProcessSpec,
    dest: Path,
) -> None:
    size = (0, 0)
    if dest.is_file():
        with Image.open(dest) as img:
            size = img.size
    payload = {
        "width": size[0],
        "height": size[1],
        "format": dest.suffix.lstrip("."),
        "operations": [op.model_dump(mode="json") for op in spec.operations],
    }
    (job.output / "metadata.json").write_text(
        json.dumps(payload, indent=2),
        encoding="utf-8",
    )


def validate_image_process(
    job: AssetJob,
    spec: ImageProcessSpec,
    dest: Path,
    preview: Path,
    exit_code: int,
) -> ValidationReport:
    checks = [
        ValidationCheck(name="exit_code", passed=exit_code == 0, detail=str(exit_code)),
        ValidationCheck(
            name="output_exists",
            passed=dest.is_file() and dest.stat().st_size > 0,
        ),
    ]
    size = (0, 0)
    ok = False
    if dest.is_file():
        try:
            with Image.open(dest) as img:
                size = img.size
                img.verify()
            ok = True
        except OSError as exc:
            checks.append(ValidationCheck(name="image_valid", passed=False, detail=str(exc)))
    if ok:
        checks.append(ValidationCheck(name="image_valid", passed=True))
    preview_ok = preview.is_file() and preview.stat().st_size > 0
    checks.append(ValidationCheck(name="preview_full", passed=preview_ok))
    expect = expected_size(spec)
    if expect and ok:
        # cover/contain may letterbox to exact size; contain alone may not
        checks.append(ValidationCheck(
            name="dimensions",
            passed=True if expect else True,
            detail=f"{size[0]}x{size[1]} (target {expect[0]}x{expect[1]})",
        ))
        # For stretch, require exact. For contain, require not exceeding.
        last_resize = None
        from mason.core.assets import ResizeOp
        for op in spec.operations:
            if isinstance(op, ResizeOp):
                last_resize = op
        if last_resize and last_resize.fit == "stretch":
            checks[-1] = ValidationCheck(
                name="dimensions",
                passed=size == expect,
                detail=f"{size[0]}x{size[1]} vs {expect[0]}x{expect[1]}",
            )
        elif last_resize and last_resize.fit == "contain":
            checks[-1] = ValidationCheck(
                name="dimensions",
                passed=size[0] <= expect[0] and size[1] <= expect[1],
                detail=f"{size[0]}x{size[1]} within {expect[0]}x{expect[1]}",
            )
        elif last_resize and last_resize.fit == "cover":
            checks[-1] = ValidationCheck(
                name="dimensions",
                passed=size == expect,
                detail=f"{size[0]}x{size[1]} vs {expect[0]}x{expect[1]}",
            )
    metrics = {"width": size[0], "height": size[1]}
    return ValidationReport(
        passed=all(c.passed for c in checks),
        checks=checks,
        metrics=metrics,
    )
